### ISSUE TITLE
Module not working when project contains date-fns@3.x

### ISSUE THREAD

**Issue by vanekj** [becem-gharbi/nuxt-naiveui#40]
Hi!

**tl;dr** This module is not working with `date-fns` version 3.x

Playground to replicate the issue: https://stackblitz.com/edit/nuxt-naiveui-datefns

I am using this module in project where I also use `date-fns` package. Recently I upgraded from `date-fns@2.30.0` to the latest (by the time of writing this issue) version `date-fns@3.0.6` which causes an error on `nuxt prepare` or `nuxt dev` commands.

When running these commands it returns the following error
```
 ERROR  Nuxt module should be a function: @bg-dev/nuxt-naiveui
```

While placing some "breakpoints" (console logs 😉) into nuxt kit `loadNuxtModuleInstance` method I get following
```
Error: Package subpath './_lib/cloneObject/index.js' is not defined by "exports" in /my/system/project/path/node_modules/date-fns/package.json
  at new NodeError (node:internal/errors:405:5)
  at exportsNotFound (node:internal/modules/esm/resolve:366:10)
  at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
  at resolveExports (node:internal/modules/cjs/loader:584:36)
  at Module._findPath (node:internal/modules/cjs/loader:658:31)
  at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
  at Function.resolve (node:internal/modules/helpers:188:19)
  at _resolve (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:251148)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:253746)
  at /my/system/project/path/node_modules/date-fns-tz/formatInTimeZone/index.js:8:37
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/naive-ui/lib/time-picker/src/TimePicker.js:13:44
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/naive-ui/lib/time-picker/index.js:7:20
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/naive-ui/lib/date-picker/src/panel/datetime.js:8:23
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/naive-ui/lib/date-picker/src/DatePicker.js:22:36
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/naive-ui/lib/date-picker/index.js:7:20
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/naive-ui/lib/components.js:41:14
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/naive-ui/lib/preset.js:30:33
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/naive-ui/lib/index.js:21:16
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at /my/system/project/path/node_modules/@bg-dev/nuxt-naiveui/dist/module.mjs:3:39
  at evalModule (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (/my/system/project/path/node_modules/jiti/dist/jiti.js:1:254371)
  at requireModule (file:///my/system/project/path/node_modules/@nuxt/kit/dist/index.mjs:2249:26)
  at loadNuxtModuleInstance (file:///my/system/project/path/node_modules/@nuxt/kit/dist/index.mjs:2483:92)
  at async installModule (file:///my/system/project/path/node_modules/@nuxt/kit/dist/index.mjs:2437:47)
  at async initNuxt (file:///my/system/project/path/node_modules/nuxt/dist/index.mjs:3822:7)
  at async loadNuxt (file:///my/system/project/path/node_modules/nuxt/dist/index.mjs:3920:5)
  at async loadNuxt (file:///my/system/project/path/node_modules/@nuxt/kit/dist/index.mjs:2603:19)
  at async Object.run (file:///my/system/project/path/node_modules/nuxi/dist/chunks/prepare.mjs:56:18)
  at async runCommand$1 (file:///my/system/project/path/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (file:///my/system/project/path/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (file:///my/system/project/path/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7)
code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

**Comment by becem-gharbi** [comment]
Hi, this seems to be a dependency resolution issue with npm. Can you try with pnpm?

**Comment by becem-gharbi** [comment]
Hi, for now you can try with yarn. I will inspect the issue later.

**Comment by becem-gharbi** [comment]
This is a problem with `date-fns-tz`, it has `date-fns` as peer-dependency with version `>=2`. However it's not yet compatible with `v3`. You can check this issue https://github.com/marnusw/date-fns-tz/issues/260.
